DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddBookings`(
  $usermod int,
  $billable tinyint(4) ,
  $recruiterid int(11) ,
  $marketerid int(11) ,
  $physid int(11) ,
$physname varchar(45) ,
  $clientid int(11) ,
  $clienttxt varchar(45) ,
  $statetxt varchar(45) ,
  $citytxt varchar(45) ,
  $credentialing_manager varchar(45) ,
  $provider_pay decimal(6,2) ,
  $billing_pay decimal(6,2) ,
  $phys_per_diem decimal(6,2) ,
  $bill_per_diem decimal(6,2) ,
  $phys_malpractice decimal(6,2) ,
  $bill_malpractice decimal(6,2) ,
  $dr_holiday_rate decimal(6,2) ,
  $cl_holiday_rate decimal(6,2) ,
  $dr_overtime decimal(6,2) ,
  $cl_overtime decimal(6,2) ,
  $dr_night_call decimal(6,2) ,
  $cl_night_call decimal(6,2) ,
  $dr_weekend decimal(6,2) ,
  $cl_weekend decimal(6,2) ,
  $dr_mileage decimal(6,2) ,
  $cl_mileage decimal(6,2) ,
  $flight_arrangedby varchar(45) ,
  $fly_from varchar(45) ,
  $fly_to varchar(45) ,
  $depart_date datetime ,
  $return_date datetime ,
  $rental_arrangedby varchar(45) ,
  $pickup_loc varchar(45) ,
  $dropoff_loc varchar(45) ,
  $rental_agency varchar(45) ,
  $housing_arrangedby varchar(45) ,
  $housing_loc varchar(45) ,
  $housing_city varchar(45) ,
  $pets int(11) ,
  $smoking int(11) ,
  $family_members varchar(45) ,
  $contract_attached int(11) ,
  $dr_confirmed int(11) ,
  $timesheets int(11) ,
  $malpractice_ins int(11) ,
  $credentials int(11) ,
  $pay_addendum int(11) ,
  $contract_ext int(11) ,
  $work_addr varchar(45) ,
  $assignment varchar(45) ,
  $deposit int(11) ,
  $prepay int(11) ,
  $deposit_amt varchar(45) ,
  $prepay_amt varchar(45),
  $book_status varchar(45) )
BEGIN

INSERT INTO bookings (
create_date,
  mod_date,
  usermod,
  billable,
  recruiterid,
  marketerid,
  physid,
physname,
  clientid,
  clienttxt,
  statetxt,
  citytxt,
  credentialing_manager,
  provider_pay,
  billing_pay,
  phys_per_diem,
  bill_per_diem,
phys_malpractice,
  bill_malpractice,
  dr_holiday_rate,
  cl_holiday_rate,
  dr_overtime,
  cl_overtime,
  dr_night_call,
  cl_night_call,
  dr_weekend,
  cl_weekend,
  dr_mileage,
  cl_mileage,
  flight_arrangedby,
  fly_from,
  fly_to,
  depart_date,
  return_date,
  rental_arrangedby,
  pickup_loc,
  dropoff_loc,
  rental_agency,
  housing_arrangedby,
  housing_loc,
  housing_city,
  pets,
  smoking,
  family_members,
  contract_attached,
  dr_confirmed,
  timesheets,
  malpractice_ins,
  credentials,
  pay_addendum,
  contract_ext,
  work_addr,
  assignment,
  deposit,
  prepay,
  deposit_amt,
  prepay_amt,
  book_status
) VALUES (
NOW(),
NOW(),
  $usermod,
  $billable,
  $recruiterid,
  $marketerid,
  $physid,
$physname,
  $clientid,
  $clienttxt,
  $statetxt,
  $citytxt,
  $credentialing_manager,
  $provider_pay,
  $billing_pay,
  $phys_per_diem,
  $bill_per_diem,
$phys_malpractice,
  $bill_malpractice,
  $dr_holiday_rate,
  $cl_holiday_rate,
  $dr_overtime,
  $cl_overtime,
  $dr_night_call,
  $cl_night_call,
  $dr_weekend,
  $cl_weekend,
  $dr_mileage,
  $cl_mileage,
  $flight_arrangedby,
  $fly_from,
  $fly_to,
  $depart_date,
  $return_date,
  $rental_arrangedby,
  $pickup_loc,
  $dropoff_loc,
  $rental_agency,
  $housing_arrangedby,
  $housing_loc,
  $housing_city,
  $pets,
  $smoking,
  $family_members,
  $contract_attached,
  $dr_confirmed,
  $timesheets,
  $malpractice_ins,
  $credentials,
  $pay_addendum,
  $contract_ext,
  $work_addr,
  $assignment,
  $deposit,
  $prepay,
  $deposit_amt,
  $prepay_amt,
  $book_status
);

SELECT LAST_INSERT_ID() AS id;

END$$
DELIMITER ;
